#!/bin/bash

# Source function library.
. /etc/init.d/functions

init_sysrepo() {
    export NP2_MODULE_DIR="/usr/share/yang/modules/netopeer2"
    export NP2_MODULE_PERMS="600"
    export NP2_MODULE_OWNER="root"
    export NP2_MODULE_GROUP="root"
    sh /usr/share/netopeer2/setup.sh
    sh /usr/share/netopeer2/merge_hostkey.sh
    sh /usr/share/netopeer2/merge_config.sh
    touch /etc/sysrepo/init
}

start() {
    test -r /etc/sysrepo/init || init_sysrepo
    start-stop-daemon --start --exec /usr/sbin/netopeer2-server -- -v 2
}

stop() {
    start-stop-daemon --stop --quiet --exec /usr/sbin/netopeer2-server
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status netopeer2-server
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0